import { Painel } from '@/components/Painel';
import { store } from '@/redux/store';
import Head from 'next/head';
import { Provider } from 'react-redux';

export default function Home() {
  return (
    <>
      <Head>
        <title>Boletim Escolar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Provider store={ store }>
          <Painel />
        </Provider>
      </main>
    </>
  )
}
